import { describe, expect, it } from 'vitest';
import { JSONB_AGG_CALLERS, jsonbAggEvidence } from './galaxy-evidence.fixture';
import { relationshipAnswer, relationshipQuestion } from './relationship-answer';

const line = (markdown: string, type: string) => markdown.split('\n').find(item => item.startsWith(`- **${type}** `)) ?? '';

describe('caller and callee questions', () => {
    it.each([
        ['Who calls JSONBAgg?', ['incoming'], 'en'],
        ['Who calls JSONBAgg? List every caller and the edge type.', ['incoming'], 'en'],
        ['List the callers of this class', ['incoming'], 'en'],
        ['Where is it called from? Show what calls it.', ['incoming'], 'en'],
        ['What is JSONBAgg called by?', ['incoming'], 'en'],
        ['What does JSONBAgg call?', ['outgoing'], 'en'],
        ['Show the callees', ['outgoing'], 'en'],
        ['Wer ruft JSONBAgg auf?', ['incoming'], 'de'],
        ['Welche Aufrufer hat die Klasse?', ['incoming'], 'de'],
        ['Was ruft JSONBAgg auf?', ['outgoing'], 'de'],
        ['Who calls it and what does it call?', ['incoming', 'outgoing'], 'en'],
    ] as const)('recognizes %s', (prompt, sides, language) => {
        expect(relationshipQuestion(prompt)).toEqual({ sides, language });
    });

    it.each(['Explain JSONBAgg', 'What does this class do?', 'Was macht diese Klasse?', 'Write a test for JSONBAgg'])('leaves %s to the model', prompt => {
        expect(relationshipQuestion(prompt)).toBeUndefined();
    });
});

describe('listed relationship answers', () => {
    it('lists every incoming relationship of JSONBAgg by edge type, CALLS first, with complete counts', () => {
        const answer = relationshipAnswer('Who calls JSONBAgg? List every caller and the edge type.', [jsonbAggEvidence()])!;
        expect(answer.markdown).toContain('Callers of `JSONBAgg` in the loaded graph. Incoming relationships: 23 from 12 symbols.');
        const calls = line(answer.markdown, 'CALLS'), tests = line(answer.markdown, 'TESTS');
        expect(answer.markdown.indexOf(calls)).toBeLessThan(answer.markdown.indexOf(tests));
        for (const text of [calls, tests]) {
            expect(text).toMatch(/from 11: /);
            for (const name of JSONB_AGG_CALLERS) expect(text).toContain(`\`${name}\``);
            expect(text).toContain('(Method, `tests/postgres_tests/test_aggregates.py`)');
            expect(text).not.toContain('more');
        }
        expect(line(answer.markdown, 'DEFINES')).toBe('- **DEFINES** from 1: `general.py` (File, `django/contrib/postgres/aggregates/general.py`)');
        // The outgoing INHERITS edges answer another question.
        expect(answer.markdown).not.toContain('INHERITS');
        expect(answer.markdown).toContain('complete for the indexed graph');
        expect(answer.markdown).toContain('not generated by the model');
    });

    it('answers callee questions with the outgoing side only and says when no CALLS edge exists', () => {
        const answer = relationshipAnswer('What does JSONBAgg call?', [jsonbAggEvidence()])!;
        expect(answer.markdown).toContain('Outgoing relationships: 2 to 2 symbols.');
        expect(answer.markdown).toContain('`JSONBAgg` has no outgoing CALLS edge in this scope.');
        expect(line(answer.markdown, 'INHERITS')).toMatch(/to 2: `OrderableAggMixin`.*`Aggregate`/);
        expect(answer.markdown).not.toContain('test_jsonb_agg');
    });

    it('answers in German for a German question', () => {
        const answer = relationshipAnswer('Wer ruft JSONBAgg auf?', [jsonbAggEvidence()])!;
        expect(answer.markdown).toContain('Aufrufer von `JSONBAgg` im geladenen Graphen. Eingehende Beziehungen: 23 von 12 Symbolen.');
        expect(line(answer.markdown, 'CALLS')).toMatch(/^- \*\*CALLS\*\* von 11: /);
        expect(answer.markdown).toContain('Ausschnitt: 1 Schritt in beide Richtungen');
    });

    it('never reports "no callers" for a side the scope did not load or while it is still loading', () => {
        expect(relationshipAnswer('Who calls JSONBAgg?', [jsonbAggEvidence({ direction: 'outbound' })])!.markdown)
            .toContain('does not follow incoming relationships');
        expect(relationshipAnswer('Who calls JSONBAgg?', [jsonbAggEvidence({ depth: 0 })])!.markdown).toContain('Expand it by one layer');
        expect(relationshipAnswer('Who calls JSONBAgg?', [jsonbAggEvidence({ state: 'loading-partial-preview' })])!.markdown)
            .toContain('still loading; this list can grow');
    });

    it('lists a bounded sample with an explicit remainder when the evidence names fewer than the count', () => {
        const many = Array.from({ length: 40 }, (_, index) => ({ source: 2000 + index, target: 32360, type: 'CALLS' }));
        const answer = relationshipAnswer('Who calls JSONBAgg?', [jsonbAggEvidence({ edges: many })])!;
        expect(line(answer.markdown, 'CALLS')).toMatch(/^- \*\*CALLS\*\* from 40: .*; \+16 more$/);
    });

    it('leaves questions about another symbol, attached non-Galaxy evidence and other questions to the model', () => {
        expect(relationshipAnswer('Who calls BaseCommand?', [jsonbAggEvidence()])).toBeUndefined();
        expect(relationshipAnswer('Who calls JSONBAgg?', [{ id: 'g', label: 'Callers', text: '{"kind":"graph-context-snapshot"}' }])).toBeUndefined();
        expect(relationshipAnswer('Explain JSONBAgg', [jsonbAggEvidence()])).toBeUndefined();
        expect(relationshipAnswer('Who calls it?', [jsonbAggEvidence()])).toBeDefined();
        expect(relationshipAnswer('Who calls `general.JSONBAgg`?', [jsonbAggEvidence()])).toBeDefined();
    });
});
