import { describe, expect, it } from 'vitest';
import { selectionEvidenceContext } from '../galaxy/selection-evidence';
import { JSONB_AGG_CALLERS, jsonbAggEvidence, largeFolderScope } from './galaxy-evidence.fixture';
import { relationshipAnswer, relationshipQuestion, relationshipSuggestion } from './relationship-answer';

const line = (markdown: string, type: string) => markdown.split('\n').find(item => item.startsWith(`- **${type}** `)) ?? '';

describe('caller and callee questions', () => {
    it.each([
        ['Who calls JSONBAgg?', ['incoming'], 'en', 'JSONBAgg'],
        ['Who calls JSONBAgg? List every caller and the edge type.', ['incoming'], 'en', 'JSONBAgg'],
        ['List the callers of this class', ['incoming'], 'en', undefined],
        ['Where is it called from? Show what calls it.', ['incoming'], 'en', undefined],
        ['What is JSONBAgg called by?', ['incoming'], 'en', 'JSONBAgg'],
        ['Which functions call JSONBAgg?', ['incoming'], 'en', 'JSONBAgg'],
        ['What functions call JSONBAgg?', ['incoming'], 'en', 'JSONBAgg'],
        ['Where is JSONBAgg called?', ['incoming'], 'en', 'JSONBAgg'],
        ['How many callers does JSONBAgg have?', ['incoming'], 'en', undefined],
        ['What does JSONBAgg call?', ['outgoing'], 'en', 'JSONBAgg'],
        ['Which functions does the JSONBAgg class call?', ['outgoing'], 'en', 'JSONBAgg'],
        ['Show the functions called by JSONBAgg', ['outgoing'], 'en', 'JSONBAgg'],
        ['Show the callees', ['outgoing'], 'en', undefined],
        ['Wer ruft JSONBAgg auf?', ['incoming'], 'de', 'JSONBAgg'],
        ['Wer ruft die Funktion auf?', ['incoming'], 'de', undefined],
        ['Welche Aufrufer hat die Klasse?', ['incoming'], 'de', undefined],
        ['Welche Funktion ruft JSONBAgg auf?', ['incoming'], 'de', 'JSONBAgg'],
        ['Welche Funktionen rufen JSONBAgg auf?', ['incoming'], 'de', 'JSONBAgg'],
        ['Welche Tests rufen JSONBAgg auf?', ['incoming'], 'de', 'JSONBAgg'],
        ['Wo wird JSONBAgg aufgerufen?', ['incoming'], 'de', 'JSONBAgg'],
        ['Von wem wird JSONBAgg aufgerufen?', ['incoming'], 'de', 'JSONBAgg'],
        ['Was ruft JSONBAgg auf?', ['outgoing'], 'de', 'JSONBAgg'],
        ['Welche Funktionen ruft JSONBAgg auf?', ['outgoing'], 'de', 'JSONBAgg'],
        ['Was wird von JSONBAgg aufgerufen?', ['outgoing'], 'de', 'JSONBAgg'],
        ['Who calls it and what does it call?', ['incoming', 'outgoing'], 'en', undefined],
        ['Who calls get_queryset?', ['incoming'], 'en', 'get_queryset'],
        ['Wer ruft as_sql auf?', ['incoming'], 'de', 'as_sql'],
        ['What does handle call?', ['outgoing'], 'en', 'handle'],
    ] as const)('recognizes %s', (prompt, sides, language, subject) => {
        expect(relationshipQuestion(prompt)).toEqual({ sides, language, ...subject ? { subject } : {} });
    });

    it.each(['Explain JSONBAgg', 'What does this class do?', 'Was macht diese Klasse?', 'Write a test for JSONBAgg',
        'Explain how the callers use JSONBAgg', 'Why does the caller pass distinct=True?', 'What would break for callers if I rename JSONBAgg?',
        'Who calls JSONBAgg and why?', 'Warum ruft der Test JSONBAgg auf?', 'Wie wird JSONBAgg von den Tests aufgerufen?'])('leaves %s to the model', prompt => {
        expect(relationshipQuestion(prompt)).toBeUndefined();
    });
});

describe('listed relationship answers', () => {
    it('lists every incoming relationship of JSONBAgg by edge type, CALLS first, with complete counts', () => {
        const answer = relationshipAnswer('Who calls JSONBAgg? List every caller and the edge type.', [jsonbAggEvidence()])!;
        expect(answer.markdown).toContain('Callers of `JSONBAgg` in the loaded graph. Incoming relationships: 23 from 12 symbols.');
        const calls = line(answer.markdown, 'CALLS'), tests = line(answer.markdown, 'TESTS');
        expect(answer.markdown.indexOf(calls)).toBeLessThan(answer.markdown.indexOf(tests));
        for (const text of [calls, tests]) {
            expect(text).toMatch(/from 11: /);
            for (const name of JSONB_AGG_CALLERS) expect(text).toContain(`\`${name}\``);
            expect(text).toContain('(Method, `tests/postgres_tests/test_aggregates.py`)');
            expect(text).not.toContain('more');
        }
        expect(line(answer.markdown, 'DEFINES')).toBe('- **DEFINES** from 1: `general.py` (File, `django/contrib/postgres/aggregates/general.py`)');
        // The outgoing INHERITS edges answer another question.
        expect(answer.markdown).not.toContain('INHERITS');
        expect(answer.markdown).toContain('complete for the indexed graph');
        expect(answer.markdown).toContain('not generated by the model');
    });

    it('answers callee questions with the outgoing side only and says when no CALLS edge exists', () => {
        const answer = relationshipAnswer('What does JSONBAgg call?', [jsonbAggEvidence()])!;
        expect(answer.markdown).toContain('Outgoing relationships: 2 to 2 symbols.');
        expect(answer.markdown).toContain('`JSONBAgg` has no outgoing CALLS edge in this scope.');
        expect(line(answer.markdown, 'INHERITS')).toMatch(/to 2: `OrderableAggMixin`.*`Aggregate`/);
        expect(answer.markdown).not.toContain('test_jsonb_agg');
    });

    it('answers in German for a German question', () => {
        const answer = relationshipAnswer('Wer ruft JSONBAgg auf?', [jsonbAggEvidence()])!;
        expect(answer.markdown).toContain('Aufrufer von `JSONBAgg` im geladenen Graphen. Eingehende Beziehungen: 23 von 12 Symbolen.');
        expect(line(answer.markdown, 'CALLS')).toMatch(/^- \*\*CALLS\*\* von 11: /);
        expect(answer.markdown).toContain('Ausschnitt: 1 Schritt in beide Richtungen');
    });

    it('never reports "no callers" for a side the scope did not load or while it is still loading', () => {
        expect(relationshipAnswer('Who calls JSONBAgg?', [jsonbAggEvidence({ direction: 'outbound' })])!.markdown)
            .toContain('does not follow incoming relationships');
        expect(relationshipAnswer('Who calls JSONBAgg?', [jsonbAggEvidence({ depth: 0 })])!.markdown).toContain('Expand it by one layer');
        expect(relationshipAnswer('Who calls JSONBAgg?', [jsonbAggEvidence({ state: 'loading-partial-preview' })])!.markdown)
            .toContain('still loading; this list can grow');
    });

    it('lists a bounded sample with an explicit remainder when the evidence names fewer than the count', () => {
        const many = Array.from({ length: 40 }, (_, index) => ({ source: 2000 + index, target: 32360, type: 'CALLS' }));
        const answer = relationshipAnswer('Who calls JSONBAgg?', [jsonbAggEvidence({ edges: many })])!;
        expect(line(answer.markdown, 'CALLS')).toMatch(/^- \*\*CALLS\*\* from 40: .*; \+16 more$/);
    });

    it('answers for a large documented scope with complete counts and every edge type', () => {
        const markdown = relationshipAnswer('What does postgres call?', [selectionEvidenceContext(largeFolderScope())])!.markdown;
        expect(markdown).toContain('Outgoing relationships: 150 to 150 symbols.');
        for (const type of ['CALLS', 'TESTS', 'USAGE', 'IMPORTS', 'DEFINES_METHOD']) expect(line(markdown, type)).toMatch(/^- \*\*\w+\*\* to 30: .*; \+\d+ more$/);
        expect(markdown).toContain('complete for the indexed graph.');
    });

    it('says so when the snapshot cut relationships instead of claiming a complete list', () => {
        const evidence = largeFolderScope();
        const cut = selectionEvidenceContext({ ...evidence, selected: { ...evidence.selected as object, notes: Array.from({ length: 13 }, () => 'n'.repeat(1200)) } });
        const markdown = relationshipAnswer('What does postgres call?', [cut])!.markdown;
        expect(markdown).not.toMatch(/to 0 symbols/);
        expect(markdown).toContain('the snapshot left part of its relationships out, so counts and names can be incomplete');
        expect(markdown).toMatch(/Outgoing relationships: left out of this snapshot\.|Outgoing relationships: \d+\./);
    });

    it('leaves questions about another symbol, attached non-Galaxy evidence and other questions to the model', () => {
        for (const prompt of ['Who calls BaseCommand?', 'Who calls get_queryset?', 'Wer ruft as_sql auf?', 'Who calls Aggregate?', 'What does handle call?',
            'How many callers does get_queryset have?']) expect(relationshipAnswer(prompt, [jsonbAggEvidence()])).toBeUndefined();
        expect(relationshipAnswer('Who calls the JSONBAgg class?', [jsonbAggEvidence()])).toBeDefined();
        expect(relationshipAnswer('Wer ruft django.contrib.postgres.aggregates.general.JSONBAgg auf?', [jsonbAggEvidence()])).toBeDefined();
        expect(relationshipAnswer('Who calls JSONBAgg?', [{ id: 'g', label: 'Callers', text: '{"kind":"graph-context-snapshot"}' }])).toBeUndefined();
        expect(relationshipAnswer('Explain JSONBAgg', [jsonbAggEvidence()])).toBeUndefined();
        expect(relationshipAnswer('Who calls it?', [jsonbAggEvidence()])).toBeDefined();
        expect(relationshipAnswer('Who calls `general.JSONBAgg`?', [jsonbAggEvidence()])).toBeDefined();
    });
});

describe('tolerant caller and callee questions (K16)', () => {
    it.each([
        ['wer ruf jsonbagg auf', ['incoming'], 'de', 'jsonbagg'],
        ['wer ruft jsonbagg auf', ['incoming'], 'de', 'jsonbagg'],
        ['Wer ruft JSONBAgg auf', ['incoming'], 'de', 'JSONBAgg'],
        ['wer rufen jsonbagg auf', ['incoming'], 'de', 'jsonbagg'],
        ['wer rugt jsonbagg auf?', ['incoming'], 'de', 'jsonbagg'],
        ['wer rfut jsonbagg auf?', ['incoming'], 'de', 'jsonbagg'],
        ['wer ruftt jsonbagg auf', ['incoming'], 'de', 'jsonbagg'],
        ['wer ruft eigentlich jsonbagg auf', ['incoming'], 'de', 'jsonbagg'],
        ['von wem wird jsonbagg aufgerufen', ['incoming'], 'de', 'jsonbagg'],
        ['von wem wird jsonbagg aufgerufn', ['incoming'], 'de', 'jsonbagg'],
        ['jsonbagg wird von wem aufgerufen?', ['incoming'], 'de', 'jsonbagg'],
        ['wo wird jsonbagg aufgeruffen', ['incoming'], 'de', 'jsonbagg'],
        ['wer hat jsonbagg aufgerufen', ['incoming'], 'de', 'jsonbagg'],
        ['aufrufer von jsonbagg', ['incoming'], 'de', 'jsonbagg'],
        ['aufrufr von jsonbagg', ['incoming'], 'de', 'jsonbagg'],
        ['was ruf jsonbagg auf', ['outgoing'], 'de', 'jsonbagg'],
        ['who cals jsonbagg', ['incoming'], 'en', 'jsonbagg'],
        ['who call JSONBAgg', ['incoming'], 'en', 'JSONBAgg'],
        ['who calsl JSONBAgg?', ['incoming'], 'en', 'JSONBAgg'],
        ['who is calling JSONBAgg', ['incoming'], 'en', 'JSONBAgg'],
        ['caller of jsonbagg', ['incoming'], 'en', 'jsonbagg'],
        ['calers of jsonbagg', ['incoming'], 'en', 'jsonbagg'],
        ['what does jsonbagg cal', ['outgoing'], 'en', 'jsonbagg'],
    ] as const)('recognizes %s despite typos, conjugation or a missing question mark', (prompt, sides, language, subject) => {
        expect(relationshipQuestion(prompt)).toEqual({ sides, language, subject });
        const markdown = relationshipAnswer(prompt, [jsonbAggEvidence()])?.markdown ?? '';
        expect(markdown).toContain('`JSONBAgg`');
        expect(markdown).toContain(language === 'de' ? 'im geladenen Graphen' : 'in the loaded graph');
    });

    it.each(['falls jsonbagg fehlt, was passiert?', 'Erkläre jsonbagg', 'who calls jsonbagg and why', 'auf jsonbagg', 'cells of jsonbagg',
        'what is jsonbagg', 'warum ruft der test jsonbagg auf', 'Wie wird JSONBAgg aufgerufen?', 'all jsonbagg tests'])('does not take %s for a list question', prompt => {
        expect(relationshipQuestion(prompt)).toBeUndefined();
        expect(relationshipSuggestion(prompt, [jsonbAggEvidence()])).toBeUndefined();
    });

    it.each([
        ['jsonbagg aufrufe?', 'de', 'incoming'],
        ['aufrufe jsonbagg', 'de', 'incoming'],
        ['wer jsonbagg ruft', 'de', 'incoming'],
        ['calls jsonbagg', 'en', 'incoming'],
        ['jsonbagg calls', 'en', 'outgoing'],
        ['jsonbagg ruft', 'de', 'outgoing'],
    ] as const)('offers the listed answer as a suggestion when %s sounds like a relationship question', (prompt, language, side) => {
        expect(relationshipQuestion(prompt)).toBeUndefined();
        const suggestion = relationshipSuggestion(prompt, [jsonbAggEvidence()])!;
        expect(suggestion.markdown).toContain(language === 'de'
            ? `Meintest du: ${side === 'incoming' ? 'Aufrufer von' : 'von'} \`JSONBAgg\`` : `Did you mean: ${side === 'incoming' ? 'callers of' : 'what'} \`JSONBAgg\``);
        expect(relationshipAnswer(suggestion.question, [jsonbAggEvidence()])?.markdown)
            .toContain(side === 'incoming' ? (language === 'de' ? 'Aufrufer von `JSONBAgg`' : 'Callers of `JSONBAgg`') : (language === 'de' ? 'Von `JSONBAgg` aufgerufen' : 'Called by `JSONBAgg`'));
    });

    it('suggests nothing for a question about another symbol', () => {
        expect(relationshipSuggestion('calls BaseCommand', [jsonbAggEvidence()])).toBeUndefined();
        expect(relationshipSuggestion('BaseCommand aufrufe', [jsonbAggEvidence()])).toBeUndefined();
    });
});
